FROM gcr.io/cloud-builders/npm
MAINTAINER example@email.com

# Based on: https://github.com/GoogleCloudPlatform/cloud-builders-community/blob/master/firebase/Dockerfile
ENV FRBTOOLS_VERSION 5.1.1

RUN npm install -g firebase-tools
COPY firebase.bash .
RUN chmod +x /firebase.bash

ENTRYPOINT ["/firebase.bash"]
